--
-- $Id: ClubDead-enUS.lua 4162 2006-11-16 19:05:44Z james $
--

local L = AceLibrary("AceLocale-2.2"):new("BeQuiet")
L:RegisterTranslations("enUS", function() return {
    ["AceConsole-Commands"] = {"/bequiet", "/bq", "/stfu"},
    ["dateformat"] = "%m/%d/%y %H:%M:%S",
    ["BeQuiet"] = true,
    ["ignoretime"] = true,
    ["set default ignore time"] = true,
    ["[#d#h#m#s]"] = true,
    ["checktime"] = true,
    ["set time in between checks for expired entries"] = true,
    ["add"] = true,
    ["add entry to BQ list"] = true,
    ["<user> [#d#h#m#s]"] = true,
    ["del"] = true,
    ["remove entry from BQ list"] = true,
    ["<user>"] = true,
    ["show"] = true,
    ["show BQ list"] = true,
    ["added %s until %s (in %s)"] = true,
    ["removed %s"] = true,
    ["%s is not on the BQ list"] = true,
    ["   %s - %s (in %s)"] = true,
    ["   %s - %s (expired)"] = true,
    ["BQ entry for %s has expired"] = true,
    ["clear"] = true,
    ["clear BQ list"] = true,
    ["current BQ list:"] = true,
    ["clearing BQ list"] = true,
    ["no entries on BQ list"] = true,
    ["%s is already on the BQ list until %s (in %s)"] = true,
    ["%s was already on the BQ list; extended until %s (in %s)"] = true,
    ["could not add %s to BQ list (possibly offline?)"] = true,
    ["could not remove %s from BQ list - will try again later"] = true,
    ["attempting to ignore %s"] = true,
    ["add_del_wait"] = true,
    ["set time to wait after adding or deleting to check if it worked"] = true,
    ["queueing %s for later addition"] = true,
    ["attempting to unignore %s"] = true,
    ["attempting to ignore %s (queued from previous failure)"] = true,
    ["giving up trying to add %s (max attempts exceeded)"] = true,
    ["upgrading config from SV %d to %d"] = true,
    ["<attempts>"] = true,
    ["max_add_attempts"] = true,
    ["set number of times to try to add someone who is offline"] = true,
    ["current BQ queued adds:"] = true,
    ["   %s - %s (in %s) - %d attempts"] = true,
    ["   %s - %s (expired) - %d attempts"] = true,
    ["giving up trying to add %s (expire time exceeded)"] = true,
    ["list"] = true,
    ["scan BQ list for queued adds or expired entries"] = true,
    ["scan"] = true,
    ["invalid duration '%s'"] = true,
    ["removing %s from add queue"] = true,
    ["invalid checktime '%s' - regular scans are disabled"] = true,
    ["Clear List"] = true,
    ["Scan List"] = true,
    ["Default Ignore Time"] = true,
    ["Check Time"] = true,
    ["Add/Delete Delay"] = true,
    ["Max Add Attempts"] = true,
    ["On BQ List"] = true,
    ["(expired)"] = true,
    ["Name"] = true,
    ["Until"] = true,
    ["In"] = true,
    ["In BQ Add Queue"] = true,
    ["Attempts"] = true,
} end)

--
-- EOF
